services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - STORMGLASS_API_KEY=mysupersecretkey
      - ALLOWED_APP_IDS=myappid,myotherappid
    depends_on:
      - redis
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./custom_locations.csv:/app/custom_locations.csv:ro
    command: ["--use-cache=false", "--debug=true"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
